# -*- coding: utf-8 -*-
"""DLLAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K796R1H9jpmv0HCMYx80MtYwsi5hgWXI
"""

!ls

#mounting
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/DATASETS/DLLAB/StudentsPerformance.csv')
df.head()

!pip install opendatasets

import opendatasets as od
od.download("https://www.kaggle.com/datasets/ritwikb3/heart-disease-statlog")

import kagglehub
path = kagglehub.dataset_download("sadiajavedd/students-academic-performance-dataset")
print("Path to dataset files: ",path)

from google.colab import files
uploaded = files.upload()

import pandas as pd
newData = pd.read_csv("StudentsPerformance.csv")
newData.head()

#keras
import pandas as pd
import tensorflow as tf
from tensorflow import keras

file = "StudentsPerformance.csv"
df = pd.read_csv(file)

df.head()